### ISSUE TITLE
Log add-on disables with easy way to re-enable

### ISSUE THREAD

**Issue by mitchelljkotler** [MuckRock/documentcloud#198]
Sometimes there is a bug which causes scheduled add-on runs to be disabled unnecessarily.  It would be good to log all disablement and be able to easily re-enable.

**Comment by duckduckgrayduck** [comment]
I would like some feedback on approach before I finish:

Approach #1
Leverage  Add-On event logs.

We already can filter by disabled events on the Add-On events section in the backend. 

When the Add-On is disabled (in addons/models.py), if we update the updated_at to the current time, and added updated_at to the admin panel for the event log, we could see which Add-Ons were disabled during a particular time window, like an outage and sort like that. That wouldn't tell us what the last event state (hourly,daily,weekly) of the Add-On was before it was disabled, but if the Add-On was disabled during the time range of an outage, we can most likely assume that it was hourly (as it would takes days or weeks to disable otherwise).

Approach #2
The other option is similar to AICreditLog, we create a new AddOnDisableLog class.

Similar to the AI Credit log:
- add a class in the Add-On model for a AddOnDisableLog

Each time the disable happens (in addons/models.py) we should record:
 -Add-On
 -User
 -the time it was updated_at (so that we can sort and see disables that happened during an outage)
 
 This can be done within the pre-existing disable handling code with a addon.addon_disable_log.create() call

-Add the Add-on disables log to admin panel
	-Add-On
	-User
	-updated_at so we can see time frames for when Add-Ons disabled during outages
	-include "Event" (disabled,hourly,daily,weekly) similar to the Add On event logs so that we can toggle to re-enable directly from the backend. 

From my current understanding, the Add-On disable handling code happens in the addons/models.py file and additionally all of the fields I've proposed to use already exist in the AddOnEventSerializer, so we don't have to make any modifications to the serializer or any views.

Approach #3 
Expands on Approach #2 by capturing the last event state before it was disabled (hourly, daily, weekly). This will require an update to the model to add a previous_event_state.

**Comment by duckduckgrayduck** [comment]
Adding reverts to previous Event state as a method in the model, make this available in the admin panel

**Comment by duckduckgrayduck** [comment]
Add date filtering similar to the AI credit log
